```{r}
det <- "mazowieckie"
if_else(det == "mazowieckie", new_homes %>% filter(voivodeship == det),new_homes)
```

```{r}
ggplot(new_homes,aes(m2))+
  geom_histogram(color = "white", fill = "#78C2AD")+
  geom_vline(xintercept = median(new_homes$m2) )

```
```{r}
new_homes %>% median(as.double(m2),na.rm = T)
```

```{r}
ggplot(new_homes,aes(price))+
  geom_histogram(color = "white", fill = "#78C2AD")+
  geom_vline(xintercept = median(new_homes$price) ) +
  scale_x_continuous(labels=function(n){format(n, scientific = FALSE)})+
  theme_minimal()
```

```{r}
list.files("./www/img",pattern = "opolskie")
```
```{r}
paste0("./www/img","/opolskie")
```

```{r}
var = stringi::stri_trans_nfd("śląskie")
str_length(var)
Encoding(var)
```

```{r}
list.files("./www/img",pattern = paste0("^",str_squish(var),"(.*)","$")
)

```

^
```{r}
paste0("^",var,".","(*)","$")
```

```{r}
list.files("./www/img")
```
```{r}
mi_counties <- map_data("county", "michigan") %>% 
  select(lon = long, lat, group, id = subregion)
head(mi_counties)
#>     lon  lat group     id
#> 1 -83.9 44.9     1 alcona
#> 2 -83.4 44.9     1 alcona
#> 3 -83.4 44.9     1 alcona
#> 4 -83.3 44.8     1 alcona
#> 5 -83.3 44.8     1 alcona
#> 6 -83.3 44.8     1 alcona```
```{r}

```

```{r}
sh <- getShape("polska")
voiv_map <- getShape("voiv")
```
```{r}
library(leaflet)
library(mapoland)
leaflet() %>% 
  addTiles() %>% 
  
  addPolygons(data = sh,
              color = "red",
              weight = 1)
```

```{r}
plot(voiv_map)
```
```{r}
df_names <- new_homes$voivodeship %>% unique() 
```


```{r}
sh_names <- voiv_map$names_utf8 %>% unique()
```
```{r}
sh_names[1]
```

```{r}
new_homes %>% left_join(voiv_map,by("voivodeship"="names_utf8"))
```
```{r}

```


```{r}
```
```{r}
library(sf)
```
```{r}
woj_sp <- read_sf("data/ne_10m_admin_1_states_provinces/")
```
```{r}
woj_sf <- woj_sp %>% filter(iso_a2 == "PL") %>% 
  select(name_pl,geometry) %>% 
  mutate(name_pl = str_remove(name_pl,"województwo ")) %>% 
  mutate(name_pl = str_remove(name_pl,"-"))
  
```
```{r}
df_map <- new_homes %>% left_join(woj_sf,by=c("voivodeship"="name_pl"))
```


```{r}
ggplot(df_map)+
  geom_sf(aes(fill=voivodeship,geometry = geometry))+
  
  theme_void()
```


```{r}
map_df <- new_homes %>% 
  group_by(voivodeship) %>% 
  summarise(number_offers=sum(n()),
            mean_price = mean(price,na.rm = T),
            median_price = median(price,na.rm = T),
            ) %>% 
  left_join(woj_sf,by=c("voivodeship"="name_pl"))
```

```{r}
ggplot(map_df)+
  geom_sf(aes(fill=number_offers,geometry = geometry))+
  theme_void()
```
```{r}
ggplot(map_df)+
  geom_sf(aes(fill=median_price,geometry = geometry))+
  geom_sf_label(aes(label = paste0(voivodeship,"\n",median_price),geometry = geometry),
                label.size = 0,
                label.padding = unit(0.2,"mm")
                )+
  scale_fill_gradient(low = "#ffffcc",high = "#006837")+
  
  
  theme_void()
```





